import AuthProvider from '@/components/auth/AuthProvider'
import Toaster from '@/components/base/toast/Toaster'
import Footer from '@/components/nav/Footer'
import Navbar from '@/components/nav/Navbar'
import ThemeProvider from '@/components/theme/ThemeProvider'
import { cn } from '@/utils'
import { Analytics } from '@vercel/analytics/next'
import { SpeedInsights } from '@vercel/speed-insights/next'
import type { Metadata } from 'next'
import { Quicksand } from 'next/font/google'
import './globals.scss'
import { getNavItems } from '@/services'

const quicksand = Quicksand({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const RootLayout = async ({
  children
}: Readonly<{
  children: React.ReactNode
}>) => {
  const navItems = await getNavItems()

  return (
    <html lang="en" className="h-full" suppressHydrationWarning>
      <body className={cn('relative antialiased', quicksand.className)}>
        <AuthProvider>
          <ThemeProvider>
            <main data-vaul-drawer-wrapper className="relative flex flex-col min-h-screen bg-background">
              <Navbar navItems={navItems}/>
              <div className="flex flex-1 justify-center">{children}</div>
              <Footer navItems={navItems}/>
            </main>
            <Analytics />
            <SpeedInsights />
            <Toaster />
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  )
}

export default RootLayout
