import Footer from '@/components/nav/Footer';
import Navbar from '@/components/nav/Navbar';
import ThemeProvider from '@/components/theme/ThemeProvider';
import { cn } from '@/utils';
import { Analytics } from '@vercel/analytics/next';
import { SpeedInsights } from '@vercel/speed-insights/next';
import type { Metadata } from 'next';
import { Quicksand } from 'next/font/google';
import { Toaster } from 'sonner';
import './globals.scss';

const quicksand = Quicksand({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const RootLayout = ({
  children
}: Readonly<{
  children: React.ReactNode
}>) => {
  return (
    <html lang="en" className="h-full" suppressHydrationWarning>
      <body className={cn('relative h-full antialiased transition-colors ease-in-out duration-300', quicksand.className)}>
        <ThemeProvider>
          <main className="relative flex flex-col min-h-screen">
            <Navbar />
            <div className="flex flex-1 justify-center">{children}</div>
            <Footer />
          </main>
          <Analytics />
          <SpeedInsights />
          <Toaster position="top-center" richColors />
        </ThemeProvider>
      </body>
    </html>
  )
}

export default RootLayout
