version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    container_name: sneakers-db
    networks:
      - sneakers-store_default

volumes:
  pgdata:
    driver: local

networks:
  sneakers-store_default:
    driver: bridge
