version: '3.8'

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    container_name: sneakers
    networks:
      - sneakers-store_default

volumes:
  pgdata:
    driver: local

networks:
  sneakers-store_default:
    driver: bridge
